# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(947, 572)
        font = QtGui.QFont()
        font.setFamily("Nova Flat")
        Form.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/icons8-combo-chart-90.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        Form.setStyleSheet("background-color: rgb(33, 43, 51);\n"
"")
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(Form)
        font = QtGui.QFont()
        font.setFamily("Nova Flat")
        self.stackedWidget.setFont(font)
        self.stackedWidget.setObjectName("stackedWidget")
        self.loginPage = QtWidgets.QWidget()
        self.loginPage.setObjectName("loginPage")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.loginPage)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame = QtWidgets.QFrame(self.loginPage)
        self.frame.setMinimumSize(QtCore.QSize(471, 513))
        self.frame.setStyleSheet("background-image: url(:/images/images/reversed.jpg);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.loginPage)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setMinimumSize(QtCore.QSize(450, 493))
        self.frame_3.setMaximumSize(QtCore.QSize(450, 493))
        self.frame_3.setStyleSheet("background-color: rgb(33, 40, 41);\n"
"border-radius: 10px\n"
"")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label = QtWidgets.QLabel(self.frame_3)
        self.label.setGeometry(QtCore.QRect(37, 50, 351, 51))
        self.label.setMinimumSize(QtCore.QSize(351, 51))
        self.label.setSizeIncrement(QtCore.QSize(0, 1))
        font = QtGui.QFont()
        font.setFamily("Nova Flat")
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(168, 168, 168);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame_3)
        self.label_2.setGeometry(QtCore.QRect(80, 120, 351, 21))
        self.label_2.setSizeIncrement(QtCore.QSize(0, 1))
        font = QtGui.QFont()
        font.setFamily("Nova Flat")
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(168, 168, 168);\n"
"\n"
"")
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame_3)
        self.label_3.setGeometry(QtCore.QRect(80, 200, 351, 21))
        self.label_3.setSizeIncrement(QtCore.QSize(0, 1))
        font = QtGui.QFont()
        font.setFamily("Nova Flat")
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(168, 168, 168);\n"
"")
        self.label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.lineEdit = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit.setGeometry(QtCore.QRect(80, 140, 271, 31))
        self.lineEdit.setStyleSheet("color: rgb(168, 168, 168);\n"
"border-bottom: 2px solid rgb(168, 168, 168);\n"
"border-radius:0px")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_2.setGeometry(QtCore.QRect(80, 220, 281, 31))
        self.lineEdit_2.setStyleSheet("color: rgb(168, 168, 168);\n"
"border-bottom: 2px solid rgb(168, 168, 168);\n"
"border-radius:0px")
        self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton = QtWidgets.QPushButton(self.frame_3)
        self.pushButton.setGeometry(QtCore.QRect(140, 320, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Nova Flat")
        self.pushButton.setFont(font)
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setStyleSheet("background-color: rgb(12, 39, 189);\n"
"border-radius:5px")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_2.setGeometry(QtCore.QRect(150, 412, 141, 31))
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_3.setGeometry(QtCore.QRect(280, 250, 81, 21))
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_3.setStyleSheet("color: rgb(255, 0, 0)")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_9 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_9.setGeometry(QtCore.QRect(320, 210, 41, 41))
        self.pushButton_9.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_9.setStyleSheet("color: rgb(168, 168, 168);\n"
"border-bottom: 2px solid rgb(168, 168, 168);\n"
"border-radius:0px")
        self.pushButton_9.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/icons8-lock-384.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_9.setIcon(icon1)
        self.pushButton_9.setIconSize(QtCore.QSize(22, 22))
        self.pushButton_9.setObjectName("pushButton_9")
        self.label_33 = QtWidgets.QLabel(self.frame_3)
        self.label_33.setGeometry(QtCore.QRect(80, 170, 271, 20))
        self.label_33.setStyleSheet("color: rgb(255, 0, 0)")
        self.label_33.setText("")
        self.label_33.setObjectName("label_33")
        self.label_34 = QtWidgets.QLabel(self.frame_3)
        self.label_34.setGeometry(QtCore.QRect(80, 250, 271, 20))
        self.label_34.setStyleSheet("color: rgb(255, 0, 0)")
        self.label_34.setText("")
        self.label_34.setObjectName("label_34")
        self.label.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.pushButton.raise_()
        self.pushButton_2.raise_()
        self.label_33.raise_()
        self.label_34.raise_()
        self.pushButton_3.raise_()
        self.lineEdit_2.raise_()
        self.lineEdit.raise_()
        self.pushButton_9.raise_()
        self.horizontalLayout_3.addWidget(self.frame_3)
        self.horizontalLayout_2.addWidget(self.frame_2)
        self.stackedWidget.addWidget(self.loginPage)
        self.SignupPage = QtWidgets.QWidget()
        self.SignupPage.setObjectName("SignupPage")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.SignupPage)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.frame_5 = QtWidgets.QFrame(self.SignupPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_5.sizePolicy().hasHeightForWidth())
        self.frame_5.setSizePolicy(sizePolicy)
        self.frame_5.setMinimumSize(QtCore.QSize(230, 491))
        self.frame_5.setMaximumSize(QtCore.QSize(500, 16777215))
        self.frame_5.setStyleSheet("background-color: rgb(117, 117, 117);")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_12 = QtWidgets.QLabel(self.frame_5)
        self.label_12.setMinimumSize(QtCore.QSize(210, 51))
        self.label_12.setMaximumSize(QtCore.QSize(211, 51))
        self.label_12.setSizeIncrement(QtCore.QSize(0, 1))
        font = QtGui.QFont()
        font.setFamily("Nova Flat")
        font.setPointSize(11)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("border-left:7px solid rgb(33, 43, 51);\n"
"background-color: rgb(100, 100, 100);\n"
"")
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_2.addWidget(self.label_12)
        self.label_13 = QtWidgets.QLabel(self.frame_5)
        self.label_13.setMaximumSize(QtCore.QSize(211, 51))
        self.label_13.setSizeIncrement(QtCore.QSize(0, 1))
        font = QtGui.QFont()
        font.setFamily("Nova Flat")
        font.setPointSize(11)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("background-color: rgb(100, 100, 100);\n"
"")
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_2.addWidget(self.label_13)
        self.label_14 = QtWidgets.QLabel(self.frame_5)
        self.label_14.setMaximumSize(QtCore.QSize(211, 51))
        self.label_14.setSizeIncrement(QtCore.QSize(0, 1))
        font = QtGui.QFont()
        font.setFamily("Nova Flat")
        font.setPointSize(11)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("background-color: rgb(100, 100, 100);\n"
"")
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_2.addWidget(self.label_14)
        self.pushButton_5 = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_5.setMinimumSize(QtCore.QSize(161, 41))
        self.pushButton_5.setMaximumSize(QtCore.QSize(205, 41))
        font = QtGui.QFont()
        font.setFamily("Nova Flat")
        font.setPointSize(10)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_5.setStyleSheet("background-color: rgb(12, 39, 189);\n"
"border-radius:5px")
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout_2.addWidget(self.pushButton_5, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_4.addWidget(self.frame_5)
        self.frame_4 = QtWidgets.QFrame(self.SignupPage)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.stackedWidget_2 = QtWidgets.QStackedWidget(self.frame_4)
        self.stackedWidget_2.setObjectName("stackedWidget_2")
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.page_3)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.frame_8 = QtWidgets.QFrame(self.page_3)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_5.addWidget(self.frame_8)
        self.frame_9 = QtWidgets.QFrame(self.page_3)
        self.frame_9.setMinimumSize(QtCore.QSize(650, 0))
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_9)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_11 = QtWidgets.QFrame(self.frame_9)
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.verticalLayout_3.addWidget(self.frame_11)
        self.frame_12 = QtWidgets.QFrame(self.frame_9)
        self.frame_12.setMinimumSize(QtCore.QSize(0, 490))
        self.frame_12.setSizeIncrement(QtCore.QSize(0, 0))
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.label_7 = QtWidgets.QLabel(self.frame_12)
        self.label_7.setGeometry(QtCore.QRect(360, 175, 351, 31))
        self.label_7.setSizeIncrement(QtCore.QSize(0, 1))
        font = QtGui.QFont()
        font.setFamily("Nova Flat")
        font.setPointSize(11)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: rgb(168, 168, 168);\n"
"\n"
"")
        self.label_7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.label_16 = QtWidgets.QLabel(self.frame_12)
        self.label_16.setGeometry(QtCore.QRect(0, -10, 641, 61))
        self.label_16.setMinimumSize(QtCore.QSize(351, 51))
        self.label_16.setSizeIncrement(QtCore.QSize(0, 1))
        font = QtGui.QFont()
        font.setFamily("Nova Flat")
        font.setPointSize(18)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("color: rgb(168, 168, 168);")
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.label_11 = QtWidgets.QLabel(self.frame_12)
        self.label_11.setGeometry(QtCore.QRect(30, 235, 321, 16))
        self.label_11.setSizeIncrement(QtCore.QSize(0, 1))
        font = QtGui.QFont()
        font.setFamily("Nova Flat")
        font.setPointSize(9)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("color: rgb(255, 0, 0);")
        self.label_11.setText("")
        self.label_11.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.label_8 = QtWidgets.QLabel(self.frame_12)
        self.label_8.setGeometry(QtCore.QRect(30, 175, 271, 31))
        self.label_8.setSizeIncrement(QtCore.QSize(0, 1))
        font = QtGui.QFont()
        font.setFamily("Nova Flat")
        font.setPointSize(11)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color: rgb(168, 168, 168);\n"
"\n"
"")
        self.label_8.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.label_5 = QtWidgets.QLabel(self.frame_12)
        self.label_5.setGeometry(QtCore.QRect(30, 73, 271, 31))
        self.label_5.setSizeIncrement(QtCore.QSize(0, 1))
        font = QtGui.QFont()
        font.setFamily("Nova Flat")
        font.setPointSize(11)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(168, 168, 168);\n"
"\n"
"")
        self.label_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.label_10 = QtWidgets.QLabel(self.frame_12)
        self.label_10.setGeometry(QtCore.QRect(360, 274, 351, 31))
        self.label_10.setSizeIncrement(QtCore.QSize(0, 1))
        font = QtGui.QFont()
        font.setFamily("Nova Flat")
        font.setPointSize(11)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("color: rgb(168, 168, 168);\n"
"\n"
"")
        self.label_10.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.frame_12)
        self.lineEdit_3.setGeometry(QtCore.QRect(30, 103, 271, 31))
        self.lineEdit_3.setStyleSheet("color: rgb(168, 168, 168);\n"
"border: 1px solid rgb(168, 168, 168);\n"
"border-radius:4px;\n"
"padding-left:5px\n"
"")
        self.lineEdit_3.setText("")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.frame_12)
        self.lineEdit_5.setGeometry(QtCore.QRect(30, 205, 271, 31))
        self.lineEdit_5.setStyleSheet("color: rgb(168, 168, 168);\n"
"border: 1px solid rgb(168, 168, 168);\n"
"border-radius:4px;\n"
"padding-left:5px\n"
"\n"
"")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.label_6 = QtWidgets.QLabel(self.frame_12)
        self.label_6.setGeometry(QtCore.QRect(360, 73, 351, 31))
        self.label_6.setSizeIncrement(QtCore.QSize(0, 1))
        font = QtGui.QFont()
        font.setFamily("Nova Flat")
        font.setPointSize(11)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: rgb(168, 168, 168);\n"
"\n"
"")
        self.label_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.frame_12)
        self.lineEdit_4.setGeometry(QtCore.QRect(360, 103, 271, 31))
        self.lineEdit_4.setStyleSheet("color: rgb(168, 168, 168);\n"
"border: 1px solid rgb(168, 168, 168);\n"
"border-radius:4px;\n"
"padding-left:5px\n"
"\n"
"")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_15 = QtWidgets.QLabel(self.frame_12)
        self.label_15.setGeometry(QtCore.QRect(38, 315, 22, 21))
        self.label_15.setSizeIncrement(QtCore.QSize(0, 1))
        font = QtGui.QFont()
        font.setFamily("Nova Flat")
        font.setPointSize(9)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet("color: rgb(168, 168, 168);\n"
"\n"
"")
        self.label_15.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName("label_15")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.frame_12)
        self.lineEdit_6.setGeometry(QtCore.QRect(360, 205, 271, 31))
        self.lineEdit_6.setStyleSheet("color: rgb(168, 168, 168);\n"
"border-bottom: 2px solid rgb(168, 168, 168);\n"
"border-radius:0px;\n"
"padding-left:5px\n"
"")
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.label_9 = QtWidgets.QLabel(self.frame_12)
        self.label_9.setGeometry(QtCore.QRect(30, 277, 271, 31))
        self.label_9.setSizeIncrement(QtCore.QSize(0, 1))
        font = QtGui.QFont()
        font.setFamily("Nova Flat")
        font.setPointSize(11)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color: rgb(168, 168, 168);\n"
"\n"
"")
        self.label_9.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.frame_12)
        self.lineEdit_8.setGeometry(QtCore.QRect(30, 309, 271, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_8.setFont(font)
        self.lineEdit_8.setStyleSheet("color: rgb(168, 168, 168);\n"
"border: 1px solid rgb(168, 168, 168);\n"
"border-radius:5px;\n"
"padding-left:30px")
        self.lineEdit_8.setText("")
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.layoutWidget = QtWidgets.QWidget(self.frame_12)
        self.layoutWidget.setGeometry(QtCore.QRect(360, 301, 191, 41))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.radioButton_3 = QtWidgets.QRadioButton(self.layoutWidget)
        self.radioButton_3.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/icons8-user-male-480.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.radioButton_3.setIcon(icon2)
        self.radioButton_3.setIconSize(QtCore.QSize(28, 28))
        self.radioButton_3.setChecked(True)
        self.radioButton_3.setObjectName("radioButton_3")
        self.horizontalLayout_8.addWidget(self.radioButton_3)
        self.radioButton_4 = QtWidgets.QRadioButton(self.layoutWidget)
        self.radioButton_4.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/icons/icons8-female-user-480.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.radioButton_4.setIcon(icon3)
        self.radioButton_4.setIconSize(QtCore.QSize(28, 28))
        self.radioButton_4.setObjectName("radioButton_4")
        self.horizontalLayout_8.addWidget(self.radioButton_4)
        self.pushButton_4 = QtWidgets.QPushButton(self.frame_12)
        self.pushButton_4.setGeometry(QtCore.QRect(250, 410, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Nova Flat")
        font.setPointSize(10)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_4.setStyleSheet("background-color: rgb(0, 193, 0);\n"
"\n"
"border-radius:5px")
        self.pushButton_4.setObjectName("pushButton_4")
        self.label_7.raise_()
        self.label_16.raise_()
        self.label_11.raise_()
        self.label_8.raise_()
        self.label_5.raise_()
        self.label_10.raise_()
        self.label_6.raise_()
        self.lineEdit_4.raise_()
        self.lineEdit_6.raise_()
        self.label_9.raise_()
        self.lineEdit_8.raise_()
        self.layoutWidget.raise_()
        self.pushButton_4.raise_()
        self.lineEdit_5.raise_()
        self.lineEdit_3.raise_()
        self.label_15.raise_()
        self.verticalLayout_3.addWidget(self.frame_12)
        self.frame_13 = QtWidgets.QFrame(self.frame_9)
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.verticalLayout_3.addWidget(self.frame_13)
        self.horizontalLayout_5.addWidget(self.frame_9)
        self.frame_10 = QtWidgets.QFrame(self.page_3)
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.horizontalLayout_5.addWidget(self.frame_10)
        self.stackedWidget_2.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.page_4)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.frame_14 = QtWidgets.QFrame(self.page_4)
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.horizontalLayout_9.addWidget(self.frame_14)
        self.frame_15 = QtWidgets.QFrame(self.page_4)
        self.frame_15.setMinimumSize(QtCore.QSize(600, 0))
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_15)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_17 = QtWidgets.QFrame(self.frame_15)
        self.frame_17.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.verticalLayout_4.addWidget(self.frame_17, 0, QtCore.Qt.AlignTop)
        self.frame_18 = QtWidgets.QFrame(self.frame_15)
        self.frame_18.setMinimumSize(QtCore.QSize(0, 530))
        self.frame_18.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_18.setObjectName("frame_18")
        self.label_18 = QtWidgets.QLabel(self.frame_18)
        self.label_18.setGeometry(QtCore.QRect(160, 210, 271, 21))
        self.label_18.setSizeIncrement(QtCore.QSize(0, 1))
        font = QtGui.QFont()
        font.setFamily("Nova Flat")
        font.setPointSize(11)
        self.label_18.setFont(font)
        self.label_18.setStyleSheet("color: rgb(168, 168, 168);\n"
"\n"
"")
        self.label_18.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_18.setObjectName("label_18")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.frame_18)
        self.lineEdit_7.setGeometry(QtCore.QRect(160, 130, 281, 31))
        self.lineEdit_7.setStyleSheet("color: rgb(168, 168, 168);\n"
"border: 1px solid rgb(168, 168, 168);\n"
"border-radius:4px;\n"
"padding-left:5px\n"
"\n"
"")
        self.lineEdit_7.setText("")
        self.lineEdit_7.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.label_20 = QtWidgets.QLabel(self.frame_18)
        self.label_20.setGeometry(QtCore.QRect(160, 160, 301, 16))
        self.label_20.setSizeIncrement(QtCore.QSize(0, 1))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        font.setKerning(True)
        self.label_20.setFont(font)
        self.label_20.setStyleSheet("color: rgb(255, 0, 4);\n"
"")
        self.label_20.setText("")
        self.label_20.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_20.setObjectName("label_20")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.frame_18)
        self.lineEdit_9.setGeometry(QtCore.QRect(160, 230, 281, 31))
        self.lineEdit_9.setStyleSheet("color: rgb(168, 168, 168);\n"
"border: 1px solid rgb(168, 168, 168);\n"
"border-radius:4px;\n"
"padding-left:5px\n"
"")
        self.lineEdit_9.setText("")
        self.lineEdit_9.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.label_19 = QtWidgets.QLabel(self.frame_18)
        self.label_19.setGeometry(QtCore.QRect(-30, -10, 701, 81))
        self.label_19.setMinimumSize(QtCore.QSize(351, 51))
        self.label_19.setSizeIncrement(QtCore.QSize(0, 1))
        font = QtGui.QFont()
        font.setFamily("Nova Flat")
        font.setPointSize(23)
        self.label_19.setFont(font)
        self.label_19.setStyleSheet("color: rgb(168, 168, 168);")
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.label_22 = QtWidgets.QLabel(self.frame_18)
        self.label_22.setGeometry(QtCore.QRect(160, 260, 301, 16))
        self.label_22.setSizeIncrement(QtCore.QSize(0, 1))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        font.setKerning(True)
        self.label_22.setFont(font)
        self.label_22.setStyleSheet("color: rgb(255, 0, 4);\n"
"")
        self.label_22.setText("")
        self.label_22.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_22.setObjectName("label_22")
        self.pushButton_8 = QtWidgets.QPushButton(self.frame_18)
        self.pushButton_8.setGeometry(QtCore.QRect(400, 130, 41, 31))
        self.pushButton_8.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_8.setStyleSheet("color: rgb(168, 168, 168);\n"
"border: 1px solid rgb(168, 168, 168);\n"
"border-left: 1px solid rgb(33, 43, 51);\n"
"border-radius:4px;\n"
"border-top-left-radius: 0px;\n"
"border-bottom-left-radius: 0px;\n"
"\n"
"\n"
"")
        self.pushButton_8.setText("")
        self.pushButton_8.setIcon(icon1)
        self.pushButton_8.setIconSize(QtCore.QSize(22, 22))
        self.pushButton_8.setObjectName("pushButton_8")
        self.label_17 = QtWidgets.QLabel(self.frame_18)
        self.label_17.setGeometry(QtCore.QRect(160, 100, 271, 31))
        self.label_17.setSizeIncrement(QtCore.QSize(0, 1))
        font = QtGui.QFont()
        font.setFamily("Nova Flat")
        font.setPointSize(11)
        self.label_17.setFont(font)
        self.label_17.setStyleSheet("color: rgb(168, 168, 168);\n"
"\n"
"")
        self.label_17.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_17.setObjectName("label_17")
        self.pushButton_7 = QtWidgets.QPushButton(self.frame_18)
        self.pushButton_7.setGeometry(QtCore.QRect(400, 230, 41, 31))
        self.pushButton_7.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_7.setStyleSheet("color: rgb(168, 168, 168);\n"
"border: 1px solid rgb(168, 168, 168);\n"
"border-left: 1px solid rgb(33, 43, 51);\n"
"border-radius:4px;\n"
"border-top-left-radius: 0px;\n"
"border-bottom-left-radius: 0px;\n"
"\n"
"\n"
"")
        self.pushButton_7.setText("")
        self.pushButton_7.setIcon(icon1)
        self.pushButton_7.setIconSize(QtCore.QSize(22, 22))
        self.pushButton_7.setObjectName("pushButton_7")
        self.checkBox = QtWidgets.QCheckBox(self.frame_18)
        self.checkBox.setGeometry(QtCore.QRect(170, 300, 261, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.checkBox.setFont(font)
        self.checkBox.setChecked(True)
        self.checkBox.setObjectName("checkBox")
        self.pushButton_6 = QtWidgets.QPushButton(self.frame_18)
        self.pushButton_6.setGeometry(QtCore.QRect(230, 370, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Nova Flat")
        font.setPointSize(10)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_6.setStyleSheet("background-color: rgb(0, 193, 0);\n"
"\n"
"border-radius:5px")
        self.pushButton_6.setCheckable(False)
        self.pushButton_6.setChecked(False)
        self.pushButton_6.setObjectName("pushButton_6")
        self.label_18.raise_()
        self.label_20.raise_()
        self.label_19.raise_()
        self.label_22.raise_()
        self.label_17.raise_()
        self.checkBox.raise_()
        self.pushButton_6.raise_()
        self.lineEdit_9.raise_()
        self.lineEdit_7.raise_()
        self.pushButton_7.raise_()
        self.pushButton_8.raise_()
        self.verticalLayout_4.addWidget(self.frame_18)
        self.frame_19 = QtWidgets.QFrame(self.frame_15)
        self.frame_19.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_19.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_19.setObjectName("frame_19")
        self.verticalLayout_4.addWidget(self.frame_19)
        self.horizontalLayout_9.addWidget(self.frame_15)
        self.frame_16 = QtWidgets.QFrame(self.page_4)
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.horizontalLayout_9.addWidget(self.frame_16)
        self.stackedWidget_2.addWidget(self.page_4)
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.page_5)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setSpacing(0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.frame_20 = QtWidgets.QFrame(self.page_5)
        self.frame_20.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_20.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_20.setObjectName("frame_20")
        self.horizontalLayout_10.addWidget(self.frame_20)
        self.frame_22 = QtWidgets.QFrame(self.page_5)
        self.frame_22.setMinimumSize(QtCore.QSize(600, 0))
        self.frame_22.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_22.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_22.setObjectName("frame_22")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_22)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_23 = QtWidgets.QFrame(self.frame_22)
        self.frame_23.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_23.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_23.setObjectName("frame_23")
        self.verticalLayout_5.addWidget(self.frame_23, 0, QtCore.Qt.AlignTop)
        self.frame_24 = QtWidgets.QFrame(self.frame_22)
        self.frame_24.setMinimumSize(QtCore.QSize(0, 505))
        self.frame_24.setMaximumSize(QtCore.QSize(580, 505))
        self.frame_24.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_24.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_24.setObjectName("frame_24")
        self.lineEdit_10 = QtWidgets.QLineEdit(self.frame_24)
        self.lineEdit_10.setGeometry(QtCore.QRect(290, 230, 271, 31))
        font = QtGui.QFont()
        font.setFamily("Nova Flat")
        font.setPointSize(10)
        self.lineEdit_10.setFont(font)
        self.lineEdit_10.setStyleSheet("color: rgb(168, 168, 168);\n"
"border-bottom: 2px solid rgb(168, 168, 168);\n"
"border-radius:0px;\n"
"padding-left:5px\n"
"")
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.label_24 = QtWidgets.QLabel(self.frame_24)
        self.label_24.setGeometry(QtCore.QRect(0, 40, 581, 101))
        self.label_24.setSizeIncrement(QtCore.QSize(0, 1))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        self.label_24.setFont(font)
        self.label_24.setStyleSheet("color: rgb(168, 168, 168);\n"
"padding:7px\n"
"\n"
"")
        self.label_24.setTextFormat(QtCore.Qt.RichText)
        self.label_24.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignTop)
        self.label_24.setWordWrap(True)
        self.label_24.setObjectName("label_24")
        self.pushButton_11 = QtWidgets.QPushButton(self.frame_24)
        self.pushButton_11.setGeometry(QtCore.QRect(190, 390, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Nova Flat")
        font.setPointSize(10)
        self.pushButton_11.setFont(font)
        self.pushButton_11.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_11.setStyleSheet("background-color: rgb(0, 193, 0);\n"
"\n"
"border-radius:5px")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/icons/icons8-upload-64 (1).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_11.setIcon(icon4)
        self.pushButton_11.setIconSize(QtCore.QSize(26, 26))
        self.pushButton_11.setCheckable(False)
        self.pushButton_11.setChecked(False)
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_10 = QtWidgets.QPushButton(self.frame_24)
        self.pushButton_10.setGeometry(QtCore.QRect(60, 230, 181, 31))
        self.pushButton_10.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_10.setStyleSheet("color: rgb(168, 168, 168);\n"
"border: 1px solid rgb(168, 168, 168);\n"
"border-radius:5px;\n"
"")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("../../../Downloads/icons8-pdf-100.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_10.setIcon(icon5)
        self.pushButton_10.setIconSize(QtCore.QSize(26, 28))
        self.pushButton_10.setObjectName("pushButton_10")
        self.label_4 = QtWidgets.QLabel(self.frame_24)
        self.label_4.setGeometry(QtCore.QRect(250, 280, 100, 100))
        self.label_4.setText("")
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.label_23 = QtWidgets.QLabel(self.frame_24)
        self.label_23.setGeometry(QtCore.QRect(-30, -20, 701, 71))
        self.label_23.setMinimumSize(QtCore.QSize(351, 51))
        self.label_23.setSizeIncrement(QtCore.QSize(0, 1))
        font = QtGui.QFont()
        font.setFamily("Nova Flat")
        font.setPointSize(18)
        self.label_23.setFont(font)
        self.label_23.setStyleSheet("color: rgb(168, 168, 168);")
        self.label_23.setAlignment(QtCore.Qt.AlignCenter)
        self.label_23.setObjectName("label_23")
        self.verticalLayout_5.addWidget(self.frame_24)
        self.frame_25 = QtWidgets.QFrame(self.frame_22)
        self.frame_25.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_25.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_25.setObjectName("frame_25")
        self.verticalLayout_5.addWidget(self.frame_25)
        self.horizontalLayout_10.addWidget(self.frame_22)
        self.frame_21 = QtWidgets.QFrame(self.page_5)
        self.frame_21.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_21.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_21.setObjectName("frame_21")
        self.horizontalLayout_10.addWidget(self.frame_21)
        self.stackedWidget_2.addWidget(self.page_5)
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setObjectName("page_6")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.page_6)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setSpacing(0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.frame_28 = QtWidgets.QFrame(self.page_6)
        self.frame_28.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_28.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_28.setObjectName("frame_28")
        self.horizontalLayout_11.addWidget(self.frame_28)
        self.frame_26 = QtWidgets.QFrame(self.page_6)
        self.frame_26.setMinimumSize(QtCore.QSize(621, 0))
        self.frame_26.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_26.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_26.setObjectName("frame_26")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_26)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame_29 = QtWidgets.QFrame(self.frame_26)
        self.frame_29.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_29.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_29.setObjectName("frame_29")
        self.verticalLayout_6.addWidget(self.frame_29, 0, QtCore.Qt.AlignTop)
        self.frame_30 = QtWidgets.QFrame(self.frame_26)
        self.frame_30.setMinimumSize(QtCore.QSize(0, 508))
        self.frame_30.setMaximumSize(QtCore.QSize(619, 508))
        self.frame_30.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_30.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_30.setObjectName("frame_30")
        self.label_26 = QtWidgets.QLabel(self.frame_30)
        self.label_26.setGeometry(QtCore.QRect(50, 200, 481, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_26.setFont(font)
        self.label_26.setStyleSheet("color: rgb(168, 168, 168);")
        self.label_26.setText("")
        self.label_26.setObjectName("label_26")
        self.pushButton_12 = QtWidgets.QPushButton(self.frame_30)
        self.pushButton_12.setGeometry(QtCore.QRect(220, 380, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Nova Flat")
        font.setPointSize(10)
        self.pushButton_12.setFont(font)
        self.pushButton_12.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_12.setStyleSheet("background-color: rgb(0, 193, 0);\n"
"\n"
"border-radius:5px")
        self.pushButton_12.setObjectName("pushButton_12")
        self.label_21 = QtWidgets.QLabel(self.frame_30)
        self.label_21.setGeometry(QtCore.QRect(120, 90, 341, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_21.setFont(font)
        self.label_21.setStyleSheet("color: rgb(168, 168, 168);")
        self.label_21.setObjectName("label_21")
        self.progressBar = QtWidgets.QProgressBar(self.frame_30)
        self.progressBar.setGeometry(QtCore.QRect(40, 260, 501, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.progressBar.setFont(font)
        self.progressBar.setStyleSheet("QProgressBar {\n"
"        border-radius: 5px;\n"
"        background-color: white;\n"
"        height: 20px;\n"
"        text-align: center;\n"
"    }\n"
"\n"
"    QProgressBar::chunk {\n"
"        background-color: blue;\n"
"        border-radius: 5px;\n"
"    }\n"
"")
        self.progressBar.setProperty("value", 24)
        self.progressBar.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar.setObjectName("progressBar")
        self.label_25 = QtWidgets.QLabel(self.frame_30)
        self.label_25.setGeometry(QtCore.QRect(0, 0, 621, 61))
        self.label_25.setMinimumSize(QtCore.QSize(351, 51))
        self.label_25.setSizeIncrement(QtCore.QSize(0, 1))
        font = QtGui.QFont()
        font.setFamily("Nova Flat")
        font.setPointSize(18)
        self.label_25.setFont(font)
        self.label_25.setStyleSheet("color: rgb(168, 168, 168);")
        self.label_25.setAlignment(QtCore.Qt.AlignCenter)
        self.label_25.setObjectName("label_25")
        self.verticalLayout_6.addWidget(self.frame_30)
        self.frame_31 = QtWidgets.QFrame(self.frame_26)
        self.frame_31.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_31.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_31.setObjectName("frame_31")
        self.verticalLayout_6.addWidget(self.frame_31)
        self.horizontalLayout_11.addWidget(self.frame_26)
        self.frame_27 = QtWidgets.QFrame(self.page_6)
        self.frame_27.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_27.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_27.setObjectName("frame_27")
        self.horizontalLayout_11.addWidget(self.frame_27)
        self.stackedWidget_2.addWidget(self.page_6)
        self.page_7 = QtWidgets.QWidget()
        self.page_7.setObjectName("page_7")
        self.label_30 = QtWidgets.QLabel(self.page_7)
        self.label_30.setGeometry(QtCore.QRect(30, 190, 281, 16))
        self.label_30.setSizeIncrement(QtCore.QSize(0, 1))
        font = QtGui.QFont()
        font.setFamily("Nova Flat")
        font.setPointSize(9)
        self.label_30.setFont(font)
        self.label_30.setStyleSheet("color: rgb(0, 193, 0);\n"
"")
        self.label_30.setText("")
        self.label_30.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_30.setObjectName("label_30")
        self.stackedWidget_2.addWidget(self.page_7)
        self.verticalLayout.addWidget(self.stackedWidget_2)
        self.horizontalLayout_4.addWidget(self.frame_4)
        self.stackedWidget.addWidget(self.SignupPage)
        self.ResetPassword = QtWidgets.QWidget()
        self.ResetPassword.setObjectName("ResetPassword")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.ResetPassword)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.frame_6 = QtWidgets.QFrame(self.ResetPassword)
        self.frame_6.setMaximumSize(QtCore.QSize(250, 16777215))
        self.frame_6.setStyleSheet("background-image: url(:/images/images/lock.jpg);")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_6.addWidget(self.frame_6)
        self.frame_7 = QtWidgets.QFrame(self.ResetPassword)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.frame_33 = QtWidgets.QFrame(self.frame_7)
        self.frame_33.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_33.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_33.setObjectName("frame_33")
        self.horizontalLayout_12.addWidget(self.frame_33)
        self.frame_32 = QtWidgets.QFrame(self.frame_7)
        self.frame_32.setMinimumSize(QtCore.QSize(600, 0))
        self.frame_32.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_32.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_32.setObjectName("frame_32")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_32)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.frame_35 = QtWidgets.QFrame(self.frame_32)
        self.frame_35.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_35.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_35.setObjectName("frame_35")
        self.verticalLayout_7.addWidget(self.frame_35)
        self.frame_36 = QtWidgets.QFrame(self.frame_32)
        self.frame_36.setMinimumSize(QtCore.QSize(580, 500))
        self.frame_36.setMaximumSize(QtCore.QSize(580, 500))
        self.frame_36.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_36.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_36.setObjectName("frame_36")
        self.label_31 = QtWidgets.QLabel(self.frame_36)
        self.label_31.setGeometry(QtCore.QRect(340, 200, 271, 31))
        self.label_31.setSizeIncrement(QtCore.QSize(0, 1))
        font = QtGui.QFont()
        font.setFamily("Nova Flat")
        font.setPointSize(11)
        self.label_31.setFont(font)
        self.label_31.setStyleSheet("color: rgb(168, 168, 168);\n"
"\n"
"")
        self.label_31.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_31.setObjectName("label_31")
        self.pushButton_16 = QtWidgets.QPushButton(self.frame_36)
        self.pushButton_16.setGeometry(QtCore.QRect(240, 430, 101, 41))
        self.pushButton_16.setMinimumSize(QtCore.QSize(100, 41))
        self.pushButton_16.setMaximumSize(QtCore.QSize(205, 41))
        font = QtGui.QFont()
        font.setFamily("Nova Flat")
        font.setPointSize(10)
        self.pushButton_16.setFont(font)
        self.pushButton_16.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_16.setStyleSheet("background-color: rgb(12, 39, 189);\n"
"border-radius:5px")
        self.pushButton_16.setObjectName("pushButton_16")
        self.pushButton_13 = QtWidgets.QPushButton(self.frame_36)
        self.pushButton_13.setGeometry(QtCore.QRect(530, 230, 41, 31))
        self.pushButton_13.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_13.setStyleSheet("color: rgb(168, 168, 168);\n"
"border: 1px solid rgb(168, 168, 168);\n"
"border-left: 1px solid rgb(33, 43, 51);\n"
"border-radius:4px;\n"
"border-top-left-radius: 0px;\n"
"border-bottom-left-radius: 0px;\n"
"\n"
"\n"
"")
        self.pushButton_13.setText("")
        self.pushButton_13.setIcon(icon1)
        self.pushButton_13.setIconSize(QtCore.QSize(22, 22))
        self.pushButton_13.setObjectName("pushButton_13")
        self.label_28 = QtWidgets.QLabel(self.frame_36)
        self.label_28.setGeometry(QtCore.QRect(10, 80, 271, 31))
        self.label_28.setSizeIncrement(QtCore.QSize(0, 1))
        font = QtGui.QFont()
        font.setFamily("Nova Flat")
        font.setPointSize(11)
        self.label_28.setFont(font)
        self.label_28.setStyleSheet("color: rgb(168, 168, 168);\n"
"\n"
"")
        self.label_28.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_28.setObjectName("label_28")
        self.label_27 = QtWidgets.QLabel(self.frame_36)
        self.label_27.setGeometry(QtCore.QRect(340, 80, 351, 31))
        self.label_27.setSizeIncrement(QtCore.QSize(0, 1))
        font = QtGui.QFont()
        font.setFamily("Nova Flat")
        font.setPointSize(11)
        self.label_27.setFont(font)
        self.label_27.setStyleSheet("color: rgb(168, 168, 168);\n"
"\n"
"")
        self.label_27.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_27.setObjectName("label_27")
        self.lineEdit_13 = QtWidgets.QLineEdit(self.frame_36)
        self.lineEdit_13.setGeometry(QtCore.QRect(340, 230, 231, 31))
        self.lineEdit_13.setStyleSheet("color: rgb(168, 168, 168);\n"
"border: 1px solid rgb(168, 168, 168);\n"
"border-radius:4px;\n"
"padding-left:5px\n"
"\n"
"")
        self.lineEdit_13.setText("")
        self.lineEdit_13.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.lineEdit_12 = QtWidgets.QLineEdit(self.frame_36)
        self.lineEdit_12.setGeometry(QtCore.QRect(10, 110, 241, 31))
        self.lineEdit_12.setStyleSheet("color: rgb(168, 168, 168);\n"
"border: 1px solid rgb(168, 168, 168);\n"
"border-radius:4px;\n"
"padding-left:5px\n"
"\n"
"")
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.pushButton_15 = QtWidgets.QPushButton(self.frame_36)
        self.pushButton_15.setGeometry(QtCore.QRect(200, 320, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Nova Flat")
        font.setPointSize(10)
        self.pushButton_15.setFont(font)
        self.pushButton_15.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_15.setStyleSheet("background-color: rgb(0, 193, 0);\n"
"\n"
"border-radius:5px")
        self.pushButton_15.setCheckable(False)
        self.pushButton_15.setChecked(False)
        self.pushButton_15.setObjectName("pushButton_15")
        self.lineEdit_11 = QtWidgets.QLineEdit(self.frame_36)
        self.lineEdit_11.setGeometry(QtCore.QRect(340, 110, 231, 31))
        self.lineEdit_11.setStyleSheet("color: rgb(168, 168, 168);\n"
"border-bottom: 2px solid rgb(168, 168, 168);\n"
"border-radius:0px;\n"
"padding-left:5px\n"
"")
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.label_32 = QtWidgets.QLabel(self.frame_36)
        self.label_32.setGeometry(QtCore.QRect(10, 200, 271, 31))
        self.label_32.setSizeIncrement(QtCore.QSize(0, 1))
        font = QtGui.QFont()
        font.setFamily("Nova Flat")
        font.setPointSize(11)
        self.label_32.setFont(font)
        self.label_32.setStyleSheet("color: rgb(168, 168, 168);\n"
"\n"
"")
        self.label_32.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_32.setObjectName("label_32")
        self.label_29 = QtWidgets.QLabel(self.frame_36)
        self.label_29.setGeometry(QtCore.QRect(-10, -10, 601, 61))
        self.label_29.setMinimumSize(QtCore.QSize(351, 51))
        self.label_29.setSizeIncrement(QtCore.QSize(0, 1))
        font = QtGui.QFont()
        font.setFamily("Nova Flat")
        font.setPointSize(25)
        self.label_29.setFont(font)
        self.label_29.setStyleSheet("color: rgb(168, 168, 168);")
        self.label_29.setAlignment(QtCore.Qt.AlignCenter)
        self.label_29.setObjectName("label_29")
        self.lineEdit_14 = QtWidgets.QLineEdit(self.frame_36)
        self.lineEdit_14.setGeometry(QtCore.QRect(10, 230, 231, 31))
        self.lineEdit_14.setStyleSheet("color: rgb(168, 168, 168);\n"
"border: 1px solid rgb(168, 168, 168);\n"
"border-radius:4px;\n"
"padding-left:5px\n"
"")
        self.lineEdit_14.setText("")
        self.lineEdit_14.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.pushButton_14 = QtWidgets.QPushButton(self.frame_36)
        self.pushButton_14.setGeometry(QtCore.QRect(210, 230, 41, 31))
        self.pushButton_14.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_14.setStyleSheet("color: rgb(168, 168, 168);\n"
"border: 1px solid rgb(168, 168, 168);\n"
"border-left: 1px solid rgb(33, 43, 51);\n"
"border-radius:4px;\n"
"border-top-left-radius: 0px;\n"
"border-bottom-left-radius: 0px;\n"
"\n"
"\n"
"")
        self.pushButton_14.setText("")
        self.pushButton_14.setIcon(icon1)
        self.pushButton_14.setIconSize(QtCore.QSize(22, 22))
        self.pushButton_14.setObjectName("pushButton_14")
        self.label_35 = QtWidgets.QLabel(self.frame_36)
        self.label_35.setGeometry(QtCore.QRect(10, 140, 251, 21))
        self.label_35.setSizeIncrement(QtCore.QSize(0, 1))
        font = QtGui.QFont()
        font.setFamily("Nova Flat")
        font.setPointSize(10)
        font.setItalic(True)
        self.label_35.setFont(font)
        self.label_35.setStyleSheet("color:rgb(255, 0, 0)\n"
"\n"
"")
        self.label_35.setText("")
        self.label_35.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_35.setObjectName("label_35")
        self.label_36 = QtWidgets.QLabel(self.frame_36)
        self.label_36.setGeometry(QtCore.QRect(10, 260, 301, 16))
        self.label_36.setSizeIncrement(QtCore.QSize(0, 1))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        font.setKerning(True)
        self.label_36.setFont(font)
        self.label_36.setStyleSheet("color: rgb(255, 0, 4);\n"
"")
        self.label_36.setText("")
        self.label_36.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_36.setObjectName("label_36")
        self.label_37 = QtWidgets.QLabel(self.frame_36)
        self.label_37.setGeometry(QtCore.QRect(340, 260, 231, 16))
        self.label_37.setSizeIncrement(QtCore.QSize(0, 1))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        font.setKerning(True)
        self.label_37.setFont(font)
        self.label_37.setStyleSheet("color: rgb(255, 0, 4);\n"
"")
        self.label_37.setText("")
        self.label_37.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_37.setObjectName("label_37")
        self.label_31.raise_()
        self.pushButton_16.raise_()
        self.label_28.raise_()
        self.label_27.raise_()
        self.pushButton_15.raise_()
        self.lineEdit_11.raise_()
        self.label_32.raise_()
        self.label_29.raise_()
        self.label_35.raise_()
        self.lineEdit_12.raise_()
        self.label_36.raise_()
        self.lineEdit_14.raise_()
        self.pushButton_14.raise_()
        self.label_37.raise_()
        self.lineEdit_13.raise_()
        self.pushButton_13.raise_()
        self.verticalLayout_7.addWidget(self.frame_36)
        self.frame_37 = QtWidgets.QFrame(self.frame_32)
        self.frame_37.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_37.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_37.setObjectName("frame_37")
        self.verticalLayout_7.addWidget(self.frame_37)
        self.horizontalLayout_12.addWidget(self.frame_32)
        self.frame_34 = QtWidgets.QFrame(self.frame_7)
        self.frame_34.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_34.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_34.setObjectName("frame_34")
        self.horizontalLayout_12.addWidget(self.frame_34)
        self.horizontalLayout_6.addWidget(self.frame_7)
        self.stackedWidget.addWidget(self.ResetPassword)
        self.Homepage = QtWidgets.QWidget()
        self.Homepage.setObjectName("Homepage")
        self.stackedWidget.addWidget(self.Homepage)
        self.horizontalLayout.addWidget(self.stackedWidget)

        self.retranslateUi(Form)
        self.stackedWidget.setCurrentIndex(0)
        self.stackedWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "M-Tracker"))
        self.label.setText(_translate("Form", "Log in"))
        self.label_2.setText(_translate("Form", "Username"))
        self.label_3.setText(_translate("Form", "Password"))
        self.pushButton.setText(_translate("Form", "Log in"))
        self.pushButton.setShortcut(_translate("Form", "Return"))
        self.pushButton_2.setText(_translate("Form", "New user? Sign up"))
        self.pushButton_3.setText(_translate("Form", "Forgot passord?"))
        self.label_12.setText(_translate("Form", "PERSONAL DETAILS"))
        self.label_13.setText(_translate("Form", "PASSWORD SETUP"))
        self.label_14.setText(_translate("Form", "UPLOAD STATEMENTS"))
        self.pushButton_5.setText(_translate("Form", "Back to Log in"))
        self.label_7.setText(_translate("Form", "Verification code*"))
        self.label_16.setText(_translate("Form", "PERSONAL DETAILS"))
        self.label_8.setText(_translate("Form", "Email address*"))
        self.label_5.setText(_translate("Form", "First name*"))
        self.label_10.setText(_translate("Form", "Gender*"))
        self.label_6.setText(_translate("Form", "Last name*"))
        self.label_15.setText(_translate("Form", "254"))
        self.label_9.setText(_translate("Form", "Phone number*"))
        self.pushButton_4.setText(_translate("Form", "Next"))
        self.pushButton_4.setShortcut(_translate("Form", "Return"))
        self.label_18.setText(_translate("Form", "Repeat password"))
        self.label_19.setText(_translate("Form", "Password setup"))
        self.label_17.setText(_translate("Form", "Enter password"))
        self.checkBox.setText(_translate("Form", "I agree to M-Tracker\'s Terms and conditions"))
        self.pushButton_6.setText(_translate("Form", "Next"))
        self.pushButton_6.setShortcut(_translate("Form", "Return"))
        self.lineEdit_10.setPlaceholderText(_translate("Form", "Statement\'s Password"))
        self.label_24.setText(_translate("Form", "As part of our registration process, we kindly request that you upload your M-Pesa statements sent by Safaricom and provide its password. We assure you that we take data security very seriously, and your information will be kept strictly confidential. We do not share any data with third parties."))
        self.pushButton_11.setText(_translate("Form", "Upload"))
        self.pushButton_11.setShortcut(_translate("Form", "Return"))
        self.pushButton_10.setText(_translate("Form", "Select M-Pesa Statement"))
        self.label_23.setText(_translate("Form", "Upload M-Pesa Statements"))
        self.pushButton_12.setText(_translate("Form", "Finish Sign Up"))
        self.pushButton_12.setShortcut(_translate("Form", "Return"))
        self.label_21.setText(_translate("Form", "Please note that this registration step may take some time."))
        self.label_25.setText(_translate("Form", "Processing Mpesa statements"))
        self.label_31.setText(_translate("Form", "Repeat password"))
        self.pushButton_16.setText(_translate("Form", "Back to Log in"))
        self.label_28.setText(_translate("Form", "Email address*"))
        self.label_27.setText(_translate("Form", "Verification code*"))
        self.pushButton_15.setText(_translate("Form", "Reset Password"))
        self.pushButton_15.setShortcut(_translate("Form", "Return"))
        self.label_32.setText(_translate("Form", "Enter new password"))
        self.label_29.setText(_translate("Form", "Reset Password"))



## My code

        self.db = mysql.connector.connect(
                host='localhost',
                password = 'root',
                user = 'root'
        )

        self.mycursor = self.db.cursor()

        self.pushButton_2.clicked.connect(self.pushButton_2_clicked)
        self.pushButton_5.clicked.connect(self.pushButton_5_clicked)
        self.pushButton_3.clicked.connect(self.pushButton_3_clicked)
        self.pushButton_16.clicked.connect(self.pushButton_5_clicked)
        self.signuppass_state = True
        self.reset_new_pass = True
        self.reset_confirm_pass = True
        self.set_password = True
        self.repeat_set_password = True
        self.pushButton_9.clicked.connect(lambda x: self.showpass(self.lineEdit_2, 0))
        self.pushButton_14.clicked.connect(lambda x: self.showpass(self.lineEdit_14, 1))
        self.pushButton_13.clicked.connect(lambda x: self.showpass(self.lineEdit_13, 2))
        self.pushButton_8.clicked.connect(lambda x: self.showpass(self.lineEdit_7, 4))
        self.pushButton_7.clicked.connect(lambda x: self.showpass(self.lineEdit_9, 3))
        self.pushButton_4.clicked.connect(self.pushButton_4_clicked)
        self.lineEdit_5.editingFinished.connect(self.lineEdit_5_edited)
        self.otp = "vgsv"
        self.signup_details = []
        self.checkBox.stateChanged.connect(self.sign_up_checkbox)
        self.pushButton_6.clicked.connect(self.pushButton_6_clicked)
        self.lineEdit_7.editingFinished.connect(self.lineEdit_7_edited)
        self.signup_pass = "None"


        self.pushButton_10.clicked.connect(self.pushButton_10_clicked)
        self.file_path_selected = False
        self.pushButton_11.clicked.connect(self.pushButton_11_clicked)

    def remove_comma(self, x):
            x = str(x)
            x = x.replace(',', '')
            return x

    def get_transaction(self, x):
            x = str(x).strip()
            if x.startswith('Merchant Payment'):
                    index = x.find(' - ') + 3
                    name = x[index:].strip().upper()

                    return 'BUY GOODS', name

            elif x.startswith('Deposit of Funds'):
                    index = x.find(' - ') + 3
                    name = x[index:].strip().upper()
                    return 'AGENT DEPOSIT', name


            elif x.startswith('OD Loan Repayment'):
                    return 'FULIZA REPAYMENT', 'FULIZA'

            elif x.startswith('OverDraft of Credit Party'):
                    return 'FULIZA TAKEN', 'FULIZA'

            elif x.startswith('M-Shwari Deposit'):
                    return 'MSHWARI DEPOSIT FROM MPESA', 'MSHWARI'

            elif x.startswith('KCB M-PESA Deposit'):
                    return 'KCB MPESA DEPOSIT FROM MPESA', 'MSHWARI'

            elif x.startswith('KCB M-PESA Withdraw'):
                    return 'KCB MPESA WITHDRAW TO MPESA', 'KCB'

            elif x.startswith('Customer Transfer of Funds Charge'):
                    return 'TRANSACTION COST', 'TRANSACTION COST'

            elif x.startswith('Customer Transfer'):
                    index = x.find(' - ') + 3
                    to_search = x[index:]
                    last_ = 1

                    for i in range(len(to_search)):
                            try:
                                    int(to_search[i])
                                    last_ = i

                            except:
                                    v = 10
                    name = x[index + last_ + 2:].strip().upper()

                    return 'SEND MONEY', name

            elif x.startswith('M-Shwari Withdraw'):
                    return 'M-SHWARI WITHDRAWAL TO MPESA', 'MSHWARI'

            elif x.startswith('Pay Bill'):
                    if x.strip() == 'Pay Bill Charge':
                            return 'PAY BILL CHARGES', 'TRANSACTION COST'
                    else:
                            index = x.find(' - ') + 3
                            end = x.lower().find('acc')
                            name = x[index:end].strip().upper()
                            return 'PAY BILL', name

            elif x.startswith('Funds received'):
                    index = x.find(' - ') + 3
                    to_search = x[index:]
                    last_ = 1

                    for i in range(len(to_search)):
                            try:
                                    int(to_search[i])
                                    last_ = i

                            except:
                                    v = 10
                    name = x[index + last_ + 2:].strip().upper()
                    return 'RECEIVE FUNDS FROM PERSON', name

            elif x.startswith('Customer Payment to Small Business') or x.startswith('Customer Send Money'):
                    index = x.find(' - ') + 3
                    to_search = x[index:]
                    last_ = 1

                    for i in range(len(to_search)):
                            try:
                                    int(to_search[i])
                                    last_ = i

                            except:
                                    v = 10
                    name = x[index + last_ + 2:].strip().upper()
                    return 'POCHI LA BIASHARA', name

            elif x.startswith('Airtime Purchase'):
                    return 'AIRTIME PURCHASE', 'AIRTIME'

            elif x.startswith('Business Payment from'):
                    index = x.find(' - ') + 3
                    end = x.lower().find('via')

                    to_search = x[index:]
                    last_ = 1

                    name = x[index:end].strip().upper()

                    return 'FUNDS RECEIVED FROM BUSINESS', name



            elif x.startswith('Buy Bundles Online'):
                    return 'BUNDLES PURCHASE', 'BUNDES PURCHASE'

            elif x.startswith('Customer Withdrawal'):
                    index = x.find(' - ') + 3
                    name = x[index:].strip().upper()
                    return 'CASH WITHDRAWAL', name

            elif x.startswith('Withdrawal Charge'):
                    return 'CASH WITHDRAWAL CHARGES', "TRANSACTION COST"

            elif x.startswith('Savings Contribution'):
                    return 'TO HUSTLER FUND SAVINGS', 'HUSTLER FUND'

            elif x.startswith('Term Loan Disbursement for H- Fund') or x.startswith(
                    'Term Loan Disbursement for H-Fund'):
                    return 'HUSTLER FUND Disbursement'.upper(), 'HUSTLER FUND'

            elif x.startswith('Term Loan Repayment for H- Fund') or x.startswith('Term Loan Repayment for H-Fund'):
                    return 'HUSTLER FUND REPAYMENT', 'HUSTLER FUND'

            else:
                    return 'UNIDENTIFIED', 'UNIDENTIFIED'

    def process_statement(self):
        username = self.yusanem
        path = 'statements\dencrypted.pdf'

        self.label_26.setText('Initializing...')
        self.progressBar.setValue(3)
        QApplication.processEvents()
        time.sleep(1)

        self.label_26.setText('Uploading your statements')
        self.progressBar.setValue(5)
        QApplication.processEvents()
        time.sleep(0.5)

        self.label_26.setText('Unlocking statements')
        self.progressBar.setValue(6)
        QApplication.processEvents()
        time.sleep(0.5)

        with open(path, 'rb') as file:
                pdf_reader = PyPDF2.PdfReader(file)
                num_pages = len(pdf_reader.pages)

        self.label_26.setText('Statements unlocked')
        self.progressBar.setValue(7)
        QApplication.processEvents()

        perc = round((42/num_pages), 2)
        status_bar_now = perc+8

        self.label_26.setText('Reading your statements...')
        self.progressBar.setValue(8)
        QApplication.processEvents()


        for page_number in range(1, num_pages + 1):


                if page_number == 1:
                        df = read_pdf(path, pages=page_number)
                        data = df[2]

                        return_df = data
                else:
                        df = read_pdf(path, pages=page_number)
                        data = df[0]

                if page_number != 1:
                        return_df = pd.concat([return_df, data])

                self.label_26.setText(f'Reading page {page_number} of your statements || This process may take a long time')
                self.progressBar.setValue(status_bar_now)
                QApplication.processEvents()
                status_bar_now += perc

        self.label_26.setText(f'Reading done...')
        self.progressBar.setValue(50)
        QApplication.processEvents()
        time.sleep(1)



        self.label_26.setText(f'Cleaning extracted data')
        self.progressBar.setValue(51)
        QApplication.processEvents()
        time.sleep(1)
        print(return_df)

        real_data = return_df.copy()

        real_data["Paid In"] = real_data["Paid In"].apply(lambda x: self.remove_comma(x))

        self.label_26.setText(f'Cleaning paid in data')
        self.progressBar.setValue(52)
        QApplication.processEvents()
        time.sleep(0.2)

        real_data["Withdrawn"] = real_data["Withdrawn"].apply(lambda x: self.remove_comma(x))

        self.label_26.setText(f'Cleaning withdrawn transactions data')
        self.progressBar.setValue(53)
        QApplication.processEvents()
        time.sleep(0.2)

        real_data["Balance"] = real_data["Balance"].apply(lambda x: self.remove_comma(x))
        self.label_26.setText(f'Cleaning balance data')
        self.progressBar.setValue(54)
        QApplication.processEvents()
        time.sleep(0.2)

        # Convert to float datatype

        real_data = real_data.astype({
                "Paid In": float,
                "Withdrawn": float,
                'Balance': float
        })
        self.label_26.setText(f'Setting right datatypes')
        self.progressBar.setValue(55)
        QApplication.processEvents()
        time.sleep(0.2)

        real_data["Details"] = real_data["Details"].apply(lambda x: x.replace('\r', ' '))
        self.label_26.setText(f'Understanding transaction type and parties')
        self.progressBar.setValue(57)
        QApplication.processEvents()
        time.sleep(0.2)

        details = list(real_data['Details'].apply(lambda x: self.get_transaction(x)).values)
        transaction_type = [i[0] for i in details]
        transaction_party = [i[1] for i in details]

        dates = real_data['Completion Time'].apply(lambda x: self.extract_date(x)).values
        self.label_26.setText(f'Understanding transaction dates')
        self.progressBar.setValue(59)
        QApplication.processEvents()
        time.sleep(0.2)


        year = [i[0] for i in dates]
        month = [i[1] for i in dates]
        date = [i[2] for i in dates]
        weekday = [i[3] for i in dates]
        hour = [i[4] for i in dates]
        minute = [i[5] for i in dates]
        second = [i[6] for i in dates]

        trasaction_day = []

        reverse_date = date.copy()
        reverse_date.reverse()
        datex = reverse_date[0]

        d = 1

        for i in reverse_date:
                if i == datex:
                        trasaction_day.append(d)
                else:
                        datex = i
                        d += 1
                        trasaction_day.append(d)

        trasaction_day.reverse()
        receipt = list(real_data["Receipt No."].values)
        self.label_26.setText(f'Getting transaction receipts')
        self.progressBar.setValue(60)
        QApplication.processEvents()
        time.sleep(0.2)


        paid_in = real_data['Paid In'].fillna('NAN_VALUE').values
        withdrawn = list(real_data['Withdrawn'].apply(lambda x: self.withdrawal_amount(x)).values)

        self.label_26.setText(f'Understanding withdrawn cash details')
        self.progressBar.setValue(61)
        QApplication.processEvents()
        time.sleep(0.2)

        transaction_data = []


        for i in range(len(paid_in)):
                try:
                        x = float(paid_in[i])
                        transaction_data.append((x, 'PAID IN'))
                except:
                        x = float(withdrawn[i])
                        transaction_data.append((x, 'WITHDRAWN'))

        print(transaction_data)



        self.label_26.setText(f'Categorising transaction data...')
        self.progressBar.setValue(61)
        QApplication.processEvents()
        time.sleep(0.2)

        transaction_amount = [i[0] for i in transaction_data]
        paid_in_or_withdrawn = [i[1] for i in transaction_data]

        self.label_26.setText(f'Categorising transaction data...')
        self.progressBar.setValue(62)
        QApplication.processEvents()
        time.sleep(0.2)

        balance = list(real_data.Balance.values)

        self.progressBar.setValue(63)
        QApplication.processEvents()
        time.sleep(0.2)


        df = pd.DataFrame({
                'receipt': receipt,
                'trasaction_day': trasaction_day,
                'year': year,
                'month': month,
                'date': date,
                'weekday': weekday,
                'hour': hour,
                'minute': minute,
                'second': second,
                'transaction_type': transaction_type,
                'transaction_party': transaction_party,
                'transaction_amount': transaction_amount,
                'paid_in_or_withdrawn': paid_in_or_withdrawn,
                'balance': balance
        })

        df.set_index('receipt', inplace=True)

        self.label_26.setText(f'Finalising...')
        self.progressBar.setValue(62)
        QApplication.processEvents()
        time.sleep(1)

        self.label_26.setText(f'Saving data for exploration...')
        self.progressBar.setValue(62)
        QApplication.processEvents()
        time.sleep(0.2)

        engine = create_engine('mysql+pymysql://root:root@localhost/mtracker')
        df.reset_index(inplace=True)
        df.to_sql(name= username, con=engine, if_exists='replace', index=False)

        self.label_26.setText(f'Extracting M-Pesa statements successfull.')
        self.progressBar.setValue(65)
        QApplication.processEvents()
        time.sleep(1)

        self.label_26.setText(f'Creating models for your data.')
        self.progressBar.setValue(66)
        QApplication.processEvents()
        time.sleep(1.5)

        self.label_26.setText(f'Getting your transaction data...')
        self.progressBar.setValue(67)
        QApplication.processEvents()
        time.sleep(1.5)

        # querry = f'SELECT * FROM mtracker.{username};'
        # print(querry)
        # engine = create_engine('mysql+pymysql://root:root@localhost/mtracker')
        # time.sleep(0.1)
        # df = pd.read_sql(querry, self.db)
        # print('done read sql')
        df.set_index('receipt', inplace=True)
        print('done 2')

        self.label_26.setText(f'Preparing for the creation of models...')
        self.progressBar.setValue(66)
        QApplication.processEvents()
        time.sleep(1.5)
        print('done 3')


        test = df.copy()

        test = test.groupby('trasaction_day').mean().reset_index()

        data = ['month', 'date']
        predict = 'transaction_amount'
        nearest_tens_balance = [round(x, -1) for x in list(test.balance.values)]
        nearest_hundreds_balance = [round(x, -2) for x in list(test.transaction_amount.values)]

        x = test[data]
        x.reset_index(inplace=True, drop=True)
        x = np.array(x)

        y = test[predict]
        y = np.array(y)

        linear = linear_model.LinearRegression()
        best = 0
        acc = 0
        trained = 0

        self.label_26.setText(f'Creating models...')
        self.progressBar.setValue(66)
        QApplication.processEvents()
        time.sleep(1.5)

        this_value = 66

        while acc < 0.6 and trained < 200000:
                x_train, x_test, y_train, y_test = sklearn.model_selection.train_test_split(x, y, test_size=0.1)

                linear.fit(x_train, y_train)
                acc = linear.score(x_test, y_test)

                if acc > best:
                        model = linear
                        print(f'Test number {trained}: {acc}')
                        best = acc

                trained += 1

                this_value += (33/200000)

                self.progressBar.setValue(round(this_value))
                QApplication.processEvents()

                if trained < 50000:
                        self.label_26.setText(f'Creating models... This might take about 10 minutes')
                        QApplication.processEvents()

                elif trained > 50000 and trained < 150000:
                        self.label_26.setText(f'Please be patient')
                        QApplication.processEvents()

                elif trained > 150000 and trained < 170000:
                        self.label_26.setText(f'Almost done... ')
                        QApplication.processEvents()

                else:
                        self.label_26.setText(f'Finishing up... ')
                        QApplication.processEvents()

        print('Done withall that ML shit')
        self.signup_details.append(model)
        self.signup_details = tuple(self.signup_details)
        print(self.signup_details)
        self.mycursor.execute('INSERT INTO mtracker.personal_details VALUES (%s, %s,%s,%s,%s,%s,%s)', self.signup_details)
        self.db.commit()

        self.progressBar.setValue(100)
        self.label_26.setText(f'Done! Press the finish button to continue')
        QApplication.processEvents()

    def withdrawal_amount(self, x):
            try:
                    if x < 0:
                            return -(x)
                    else:
                            return x
            except:
                    return x

    def extract_date(self, date):
            date = parser.parse(date)
            return (date.year, date.month, date.day, date.weekday(), date.hour, date.minute, date.second)

    def pushButton_11_clicked(self):
        password = self.lineEdit_10.text()
        if self.file_path_selected is True:
                try:

                        with pikepdf.open(self.file_path, password=password) as pdf:
                                pdf.save('statements\dencrypted.pdf')

                        path = r":/gifs/gifs/icons8-spinner.gif"

                        movie = QMovie(path)
                        timed = QTimer()
                        self.label_4.setMovie(movie)
                        movie.start()
                        timed.singleShot(1000, self.this_f_un_c)



                except:
                        messagebox = QMessageBox()
                        messagebox.setWindowTitle("Invalid password")
                        messagebox.setIcon(QMessageBox.Warning)
                        messagebox.setText("Invalid M-Pesa statement's password.\n"
                                           "Please enter a valid password or \n"
                                           "choose the correct statements")
                        x = messagebox.exec_()

        else:
                messagebox = QMessageBox()
                messagebox.setWindowTitle("Select statements")
                messagebox.setIcon(QMessageBox.Warning)
                messagebox.setText("Please select your valid mpesa statements!")
                x = messagebox.exec_()

    def this_f_un_c(self):
        self.pushButton_5.setEnabled(False)
        self.pushButton_12.hide()
        self.label_26.setText('Initializing...')
        self.progressBar.setValue(1)
        QApplication.processEvents()
        self.stackedWidget_2.setCurrentWidget(self.page_6)
        self.label_4.clear()
        self.process_statement()
        self.pushButton_12.show()


    def pushButton_10_clicked(self):
        fileDialog = QFileDialog()
        fileDialog.setNameFilter("PDF file (*.pdf)")
        self.file_path, _ = fileDialog.getOpenFileName(Form, "Select M-Pesa statement", "",
                                                  "PDF (*.pdf)")

        file_name = os.path.basename(self.file_path)

        if file_name.startswith('MPESA_Statement'):
                self.pushButton_10.setStyleSheet('color: rgb(168, 168, 168);'
                                                 'border: 1px solid rgb(168, 168, 168);'
                                                 'border-radius:5px;')
                self.file_path_selected = True

        else:
                self.pushButton_10.setStyleSheet('color: rgb(255, 0, 4); '
                                                 'border: 1px solid rgb(255, 0, 4); '
                                                 'border-radius:5px;')
                self.file_path_selected = False


    def lineEdit_7_edited(self):
            password = self.lineEdit_7.text()
            has_num = any(i.isdigit() for i in password)
            if len(password) < 8:
                self.label_20.setText('Password is too short')
                self.signup_pass = "Short"
            elif has_num is False:
                    self.label_20.setText('Password must include a number')
                    self.signup_pass = "No number"

            else:
                    self.label_20.setText('')
                    self.signup_pass = "Good"

    def pushButton_6_clicked(self):
            # self.stackedWidget_2.setCurrentWidget(self.page_5)
            # self.update_signup_labels()
            if self.signup_pass == 'Good':
                    if self.lineEdit_7.text() == self.lineEdit_9.text():
                            self.stackedWidget_2.setCurrentWidget(self.page_5)
                            self.update_signup_labels()
                    else:
                            self.label_22.setText('Passwords do not match')

            elif self.signup_pass == "No number":
                    messagebox = QMessageBox()
                    messagebox.setWindowTitle("Password")
                    messagebox.setIcon(QMessageBox.Warning)
                    messagebox.setText("Password is too short!")
                    x = messagebox.exec_()

            elif self.signup_pass == "No number":
                    messagebox = QMessageBox()
                    messagebox.setWindowTitle("Password")
                    messagebox.setIcon(QMessageBox.Warning)
                    messagebox.setText("Password must include a number!")
                    x = messagebox.exec_()


    def sign_up_checkbox(self, state):
            if state == Qt.Checked:
                    self.pushButton_6.setEnabled(True)
            else:
                    self.pushButton_6.setEnabled(False)

    def sendmail(self, send_email_address, message):
            server = smtplib.SMTP('smtp.gmail.com', 587)
            email_password = "awfocntdjwcygghj"
            QApplication.processEvents()

            server.ehlo()
            server.starttls()
            server.ehlo()
            server.login("assistant.mtracker@gmail.com", email_password)
            QApplication.processEvents()

            server.sendmail(
                    "M-Tracker",
                    send_email_address,
                    message)
            QApplication.processEvents()


    def lineEdit_5_edited(self):
        email = self.lineEdit_5.text()
        otp = self.get_otp()
        self.otp = otp

        company = "M-Tracker"
        body = f"Hello,\n\n" \
               f"Thank you for your interest in M-Tracker. To complete your registration process, please use the " \
               f"following verification code: \n\n{otp}\n\nPlease enter this code on the verification page within the" \
               f" next 15 minutes to complete the verification process. \nIf you did not request this code, " \
               f"please disregard this email and do not share the code with anyone. \nIf you have any questions or " \
               f"concerns, please feel free to contact our support team at assistant.mtracker@gmail.com. \n\nThank you " \
               f"for choosing M-Tracker! \n\nBest regards, \n\n{company}."

        subject = "Your Verification Code"

        message = f'subject: {subject} \n\n{body}'
        try:
                self.sendmail(email, message)
                self.label_11.setStyleSheet('color: rgb(0, 193, 0);')
                self.label_11.setText("Verification code to your email address")

        except:
                self.label_11.setStyleSheet('color: rgb(255, 0, 0);')
                self.label_11.setText("Error sending verification code to your email address")



    def get_otp(self):
            otp = ""
            for i in range(6):
                    otp = otp + (str(random.randint(0, 9)))

            QApplication.processEvents()

            return otp

    def username_generator(self, name):
        name = name.lower()
        try:
                i = 0
                done = False
                while done is False:
                        querry = 'SELECT COUNT(*) FROM mtracker.personal_details WHERE username = "%s";'
                        self.mycursor.execute(querry, (name,))
                        number = [i for i in self.mycursor][0][0]

                        if number == 0:
                                done = True
                                return name
                        else:
                                name = f'{name}{i}'
                                i += 1

        except:
                return 'error101__'


    def pushButton_4_clicked(self):
            # self.stackedWidget_2.setCurrentWidget(self.page_4)
            # self.update_signup_labels()
            # self.yusanem = 'username'
        fname = self.lineEdit_3.text()
        if fname == "":
                fname_done = False
        else:
                fname_done = True
        lname = self.lineEdit_4.text()
        if lname == "":
                lname_done = False
        else:
                lname_done = True
        email = self.lineEdit_5.text()
        otp = self.lineEdit_6.text()
        if otp == self.otp:
                otp_done = True
        else:
                otp_done = False
        phone = self.lineEdit_8.text()
        if len(phone) == 9:
                try:
                        int(phone)
                        phone_done = True
                        phone = f'254{phone}'
                except:
                        phone_done = False
        else:
                phone_done = False

        if self.radioButton_3.isChecked():
                gender = "Male"
        else:
                gender = 'Female'


        if fname_done is True and lname_done is True and phone_done is True and otp_done is True:
                username = self.username_generator(fname.lower())
                self.yusanem = username.lower()
                print(username)
                if username == 'error101__':
                        messagebox = QMessageBox()
                        messagebox.setWindowTitle("Error generating username")
                        messagebox.setIcon(QMessageBox.Warning)
                        messagebox.setText("There was an error generating your username\n"
                                           "Please restart M-Tracker!")
                        x = messagebox.exec_()
                else:
                        self.signup_details = [username, fname, lname, email, phone, gender]
                        print(self.signup_details)
                        self.stackedWidget_2.setCurrentWidget(self.page_4)
                        self.update_signup_labels()
        elif fname_done is False:
                messagebox = QMessageBox()
                messagebox.setWindowTitle("First name")
                messagebox.setIcon(QMessageBox.Warning)
                messagebox.setText("First name must not be blank!")
                x = messagebox.exec_()
        elif lname_done is False:
                messagebox = QMessageBox()
                messagebox.setWindowTitle("Last name")
                messagebox.setIcon(QMessageBox.Warning)
                messagebox.setText("Last name must not be blank!")
                x = messagebox.exec_()
        elif phone_done is False:
                messagebox = QMessageBox()
                messagebox.setWindowTitle("Phone number")
                messagebox.setIcon(QMessageBox.Warning)
                messagebox.setText("Please enter a valid phone number!")
                x = messagebox.exec_()
        elif otp_done is False:
                messagebox = QMessageBox()
                messagebox.setWindowTitle("Verification code")
                messagebox.setIcon(QMessageBox.Warning)
                messagebox.setText("Invalid verification code\nCheck the email in the spam folder!")
                x = messagebox.exec_()


    def update_signup_labels(self):
        current_widget = self.stackedWidget_2.currentIndex()
        if current_widget == 0:
                self.label_12.setStyleSheet('border-left:7px solid rgb(33, 43, 51); '
                                            'background-color: rgb(100, 100, 100);')
                self.label_13.setStyleSheet('background-color: rgb(100, 100, 100);')
                self.label_14.setStyleSheet('background-color: rgb(100, 100, 100);')
        elif current_widget == 1:
                self.label_13.setStyleSheet('border-left:7px solid rgb(33, 43, 51); '
                                            'background-color: rgb(100, 100, 100);')
                self.label_12.setStyleSheet('background-color: rgb(100, 100, 100);')
                self.label_14.setStyleSheet('background-color: rgb(100, 100, 100);')
        else:
                self.label_14.setStyleSheet('border-left:7px solid rgb(33, 43, 51); '
                                            'background-color: rgb(100, 100, 100);')
                self.label_12.setStyleSheet('background-color: rgb(100, 100, 100);')
                self.label_13.setStyleSheet('background-color: rgb(100, 100, 100);')


    def showpass(self, led, state_index):
            if state_index == 0:
                    if self.signuppass_state is True:
                        led.setEchoMode(QtWidgets.QLineEdit.Normal)
                        icon1 = QtGui.QIcon()
                        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/icons8-open-lock-384.png"), QtGui.QIcon.Normal,
                                        QtGui.QIcon.Off)
                        self.pushButton_9.setIcon(icon1)
                        self.signuppass_state = False
                    else:
                        led.setEchoMode(QtWidgets.QLineEdit.Password)
                        icon1 = QtGui.QIcon()
                        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/icons8-lock-384.png"), QtGui.QIcon.Normal,
                                        QtGui.QIcon.Off)
                        self.pushButton_9.setIcon(icon1)
                        self.signuppass_state = True

            elif state_index == 1:
                    if self.reset_new_pass is True:
                        led.setEchoMode(QtWidgets.QLineEdit.Normal)
                        icon1 = QtGui.QIcon()
                        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/icons8-open-lock-384.png"), QtGui.QIcon.Normal,
                                        QtGui.QIcon.Off)
                        self.pushButton_14.setIcon(icon1)
                        self.reset_new_pass = False
                    else:
                        led.setEchoMode(QtWidgets.QLineEdit.Password)
                        icon1 = QtGui.QIcon()
                        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/icons8-lock-384.png"), QtGui.QIcon.Normal,
                                        QtGui.QIcon.Off)
                        self.pushButton_14.setIcon(icon1)
                        self.reset_new_pass = True

            elif state_index == 2:
                    if self.reset_confirm_pass is True:
                        led.setEchoMode(QtWidgets.QLineEdit.Normal)
                        icon1 = QtGui.QIcon()
                        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/icons8-open-lock-384.png"), QtGui.QIcon.Normal,
                                        QtGui.QIcon.Off)
                        self.pushButton_13.setIcon(icon1)
                        self.reset_confirm_pass = False
                    else:
                        led.setEchoMode(QtWidgets.QLineEdit.Password)
                        icon1 = QtGui.QIcon()
                        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/icons8-lock-384.png"), QtGui.QIcon.Normal,
                                        QtGui.QIcon.Off)
                        self.pushButton_13.setIcon(icon1)
                        self.reset_confirm_pass = True

            elif state_index == 3:
                    if self.repeat_set_password is True:
                        led.setEchoMode(QtWidgets.QLineEdit.Normal)
                        icon1 = QtGui.QIcon()
                        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/icons8-open-lock-384.png"), QtGui.QIcon.Normal,
                                        QtGui.QIcon.Off)
                        self.pushButton_7.setIcon(icon1)
                        self.repeat_set_password = False
                    else:
                        led.setEchoMode(QtWidgets.QLineEdit.Password)
                        icon1 = QtGui.QIcon()
                        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/icons8-lock-384.png"), QtGui.QIcon.Normal,
                                        QtGui.QIcon.Off)
                        self.pushButton_7.setIcon(icon1)
                        self.repeat_set_password = True

            elif state_index == 4:
                    if self.set_password is True:
                        led.setEchoMode(QtWidgets.QLineEdit.Normal)
                        icon1 = QtGui.QIcon()
                        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/icons8-open-lock-384.png"), QtGui.QIcon.Normal,
                                        QtGui.QIcon.Off)
                        self.pushButton_8.setIcon(icon1)
                        self.set_password = False
                    else:
                        led.setEchoMode(QtWidgets.QLineEdit.Password)
                        icon1 = QtGui.QIcon()
                        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/icons8-lock-384.png"), QtGui.QIcon.Normal,
                                        QtGui.QIcon.Off)
                        self.pushButton_8.setIcon(icon1)
                        self.set_password = True

    def pushButton_3_clicked(self):
            self.stackedWidget.setCurrentWidget(self.ResetPassword)

    def pushButton_2_clicked(self):
            self.stackedWidget.setCurrentWidget(self.SignupPage)
            self.stackedWidget_2.setCurrentWidget(self.page_3)

            self.update_signup_labels()
            QApplication.processEvents()

    def pushButton_5_clicked(self):
        self.stackedWidget.setCurrentWidget(self.loginPage)
        self.update_signup_labels()
        QApplication.processEvents()


import resources_rc
import random
import smtplib
from PyQt5.QtWidgets import QMessageBox, QFileDialog, QApplication, QMainWindow, QProgressBar, \
        QPushButton, QVBoxLayout, QWidget, QLabel
from PyQt5.QtCore import Qt, QTimer
from PyQt5.QtGui import QMovie
import os
import pandas as pd
import numpy as np
from tabula import read_pdf
import PyPDF2
import matplotlib.pyplot as plt
import pikepdf
from sqlalchemy import create_engine
from dateutil import parser
import mysql.connector
import time
import sklearn
from sklearn import linear_model
import mysql.connector
from matplotlib import pyplot as plt
import pickle



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
